INSERT INTO USER (USER_ID,PASSWORD,NAME,EMAIL,CREATE_DATE)VALUES ('cis','1111','이순신','lss@gmail.com',CURRENT_TIMESTAMP());
INSERT INTO USER (USER_ID,PASSWORD,NAME,EMAIL,CREATE_DATE)VALUES ('hgd','1111','홍길동','hgd@gmail.com',CURRENT_TIMESTAMP());
INSERT INTO QUESTION (TITLE,CONTENTS,WRITER_ID,CREATE_DATE) VALUES('Ruby란 무언인가', '루비는',1,CURRENT_TIMESTAMP());
INSERT INTO QUESTION (TITLE,CONTENTS,WRITER_ID,CREATE_DATE) VALUES('두번째 아이디글쓰기', '잘되는것인지',2,CURRENT_TIMESTAMP());
